


-- ========================================================================
-- Author: Albert Rodriguez
-- ALTER date: 29/08/17
-- Revision: 
-- Description: Procedimiento que calcula los importes
-- ========================================================================

/*
exec [dbo].[pCalcularImp] '01', 'SF', '   1901239', '4300000000014', 3
*/

CREATE PROCEDURE [dbo].[pCalcularImp]
	@EMPRESA CHAR(2)
	, @LETRA CHAR(2)
	, @NUMERO char(10)
	, @CLIENTE char(20)
	, @TIPODOC INT
AS

BEGIN TRY

	-- Declaración variables
	DECLARE @Mensaje varchar(max), @MensajeError varchar(max)
	, @cSQL NVARCHAR(max), @cSQL1 NVARCHAR(max), @GESTION CHAR(8), @GESTIONout CHAR(8), @COMUNES CHAR(10)
	, @ParmDefinition nvarchar(max), @TABLECAB char(20), @TABLEDET char(20), @TITULOIMPORTE CHAR(20)

	-- 1.0 Asignación valor variables

	-- Nombre BBDD Comunes (único campo variable para cada cliente)
	SET @COMUNES = (SELECT '['+LTRIM(rTRIM(COMUN))+']' FROM CONFIGURACION_SQL)

	-- Nombre BBDD Ejercicio
	SET @cSQL = N'	SELECT @GESTIONout=''[''+LTRIM(RTRIM(RUTA))+'']'' FROM '+@COMUNES+'.DBO.EJERCICI WHERE PREDET=1';
	SET @ParmDefinition = N'@GESTIONout VARCHAR(8) OUTPUT'; 
	EXECUTE sp_executesql @cSQL, @ParmDefinition, @GESTIONout=@GESTION OUTPUT; 

	-- Tabla Documento
	IF @TIPODOC = 2 -- PEDIDO
		BEGIN
			SET @TABLECAB = 'C_PEDIVE'
			SET @TABLEDET = 'D_PEDIVE'
			SET @TITULOIMPORTE = 'TOTALPED'
		END 
	IF @TIPODOC = 3 -- PRESUPUESTO
		BEGIN
			SET @TABLECAB = 'C_PRESUV'
			SET @TABLEDET = 'D_PRESUV'
			SET @TITULOIMPORTE = 'IMPORTE'
		END 

	-- 2.0 / Recalcular Importes
	set @cSQL = '
	declare @TOTALDOC numeric(15,6), @PVERDECLI bit

	UPDATE '+@GESTION+'.DBO.'+@TABLEDET+' SET
		PRECIOIVA = CASE WHEN C.IVA_INC=0 
			THEN d.PRECIO+(d.PRECIO*((IVA.IVA/100)))+(case when cli.RECARGO = 1 then d.precio*(IVA.RECARG/100) else 0.00 end)
			ELSE PRECIO
		END,
		PRECIODIV = CASE WHEN C.IVA_INC=0 
			THEN PRECIO
			ELSE d.PRECIO+(d.PRECIO*((IVA.IVA/100)))+(case when cli.RECARGO = 1 then d.precio*(IVA.RECARG/100) else 0.00 end)
		END,
		PREDIVIVA = CASE WHEN C.IVA_INC=0 
			THEN d.PRECIO+(d.PRECIO*((IVA.IVA/100)))+(case when cli.RECARGO = 1 then d.precio*(IVA.RECARG/100) else 0.00 end)
			ELSE PRECIO
		END
		FROM '+@GESTION+'.DBO.'+@TABLECAB+' C 
		INNER JOIN '+@GESTION+'.DBO.'+@TABLEDET+' D ON D.EMPRESA=C.EMPRESA AND D.NUMERO=C.NUMERO AND D.LETRA=C.LETRA
		INNER JOIN '+@GESTION+'.DBO.CLIENTES CLI ON CLI.CODIGO=C.CLIENTE
		INNER JOIN '+@GESTION+'.DBO.tipo_iva IVA ON IVA.CODIGO=D.TIPO_IVA
	WHERE C.EMPRESA='''+@empresa+''' AND C.NUMERO='''+@NUMERO+''' AND C.LETRA='''+@LETRA+'''

	-- Calcular Importes lineales					
	UPDATE '+@GESTION+'.DBO.'+@TABLEDET+' SET
			IMPORTE=ROUND((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIO ELSE PESO*PRECIO END)
					-((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIO ELSE PESO*PRECIO END)*(DTO1/100))
					-(((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIO ELSE PESO*PRECIO END)
					-(CASE WHEN PESO=0.00 THEN UNIDADES*PRECIO ELSE PESO*PRECIO END)*(DTO1/100))*(DTO2/100)),2),

			IMPORTEIVA=ROUND((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIOIVA ELSE PESO*PRECIOIVA END)
					-((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIOIVA ELSE PESO*PRECIOIVA END)*(DTO1/100))
					-(((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIOIVA ELSE PESO*PRECIOIVA END)
					-(CASE WHEN PESO=0.00 THEN UNIDADES*PRECIOIVA ELSE PESO*PRECIOIVA END)*(DTO1/100))*(DTO2/100)),2),

			IMPORTEDIV=ROUND((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIODIV ELSE PESO*PRECIODIV END)
					-((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIODIV ELSE PESO*PRECIODIV END)*(DTO1/100))
					-(((CASE WHEN PESO=0.00 THEN UNIDADES*PRECIODIV ELSE PESO*PRECIODIV END)
					-(CASE WHEN PESO=0.00 THEN UNIDADES*PRECIODIV ELSE PESO*PRECIODIV END)*(DTO1/100))*(DTO2/100)),2),

			IMPDIVIVA=ROUND((CASE WHEN PESO=0.00 THEN UNIDADES*PREDIVIVA ELSE PESO*PREDIVIVA END)
					-((CASE WHEN PESO=0.00 THEN UNIDADES*PREDIVIVA ELSE PESO*PREDIVIVA END)*(DTO1/100))
					-(((CASE WHEN PESO=0.00 THEN UNIDADES*PREDIVIVA ELSE PESO*PREDIVIVA END)
					-(CASE WHEN PESO=0.00 THEN UNIDADES*PREDIVIVA ELSE PESO*PREDIVIVA END)*(DTO1/100))*(DTO2/100)),2)
	WHERE EMPRESA='''+@empresa+''' AND LTRIM(RTRIM(NUMERO))=LTRIM(RTRIM('''+@NUMERO+''')) AND LETRA='''+@LETRA+''' 
	
	-- ACTUALIZAR PVERDE
	select @pverdecli=PVERDE from '+@GESTION+'.dbo.clientes WHERE CODIGO='''+@CLIENTE+'''
	IF @PVERDECLI=0
			UPDATE '+@GESTION+'.DBO.'+@TABLEDET+' SET PVERDE=ROUND(CASE WHEN D.PESO=0.00 THEN D.UNIDADES*A.P_IMPORTE ELSE D.PESO*A.P_IMPORTE END,2)
			FROM '+@GESTION+'.DBO.'+@TABLEDET+' D INNER JOIN '+@GESTION+'.DBO.ARTICULO A ON A.CODIGO=D.ARTICULO AND A.PVERDE=1
			WHERE EMPRESA='''+@empresa+'''AND LTRIM(RTRIM(NUMERO))=LTRIM(RTRIM('''+@NUMERO+''')) AND LETRA='''+@LETRA+'''
	'
	set @cSQL1 = '
	-- ACTUALIZAR IMPORTES '+@TABLECAB+'
	UPDATE '+@GESTION+'.DBO.'+@TABLECAB+' SET '+@TITULOIMPORTE+'=D.IMPORTE, IMPDIVISA=D.IMPDIVISA, PESO=D.PESO, LITROS=D.LITROS
	FROM '+@GESTION+'.DBO.'+@TABLECAB+' C
	INNER JOIN (SELECT MAX(D.EMPRESA) AS EMPRESA, MAX(D.NUMERO) AS NUMERO, MAX(D.LETRA) AS LETRA, SUM(D.IMPORTE)+SUM(D.PVERDE) AS IMPORTE,
	SUM(D.IMPORTEDIV)+SUM(D.PVERDE) AS IMPDIVISA, SUM(D.IMPORTEIVA) AS IMPORTEIVA, SUM(D.PVERDE) AS PVERDE,
	SUM(CASE WHEN D.PESO!=0.00 THEN D.UNIDADES*D.COSTE ELSE D.PESO*D.UNIDADES END) AS COSTE
	, SUM(D.UNIDADES*(CASE WHEN D.PESO=0.00 THEN CAST(CASE WHEN LTRIM(RTRIM(A.PESO))='''' THEN ''0.00'' ELSE A.PESO END AS DECIMAL(10,2)) ELSE D.PESO END)) AS PESO
	, SUM(D.UNIDADES*(CAST(CASE WHEN LTRIM(RTRIM(A.LITROS))='''' THEN ''0.00'' ELSE A.LITROS END AS DECIMAL(10,2)))) AS LITROS
	FROM '+@GESTION+'.DBO.'+@TABLEDET+' D INNER JOIN '+@GESTION+'.DBO.ARTICULO A ON A.CODIGO=D.ARTICULO
	WHERE D.EMPRESA='''+@empresa+''' AND LTRIM(RTRIM(D.NUMERO))=LTRIM(RTRIM('''+@NUMERO+''')) AND D.LETRA='''+@LETRA+''') D ON D.EMPRESA+D.NUMERO+D.LETRA=C.EMPRESA+C.NUMERO+C.LETRA
	WHERE C.EMPRESA='''+@empresa+''' AND LTRIM(RTRIM(C.NUMERO))=LTRIM(RTRIM('''+@NUMERO+''')) AND C.LETRA='''+@LETRA+'''  

	-- Calcular TOTALDOC
	UPDATE '+@GESTION+'.DBO.C_PEDIVE SET TOTALDOC=D.TOTALDOC FROM '+@GESTION+'.DBO.C_PEDIVE C INNER JOIN (SELECT A.EMPRESA, A.NUMERO, A.LETRA, coalesce(CONVERT(DECIMAL(16,2),sum(totimpiva)),0.00)  AS TOTALDOC
	from (SELECT C.EMPRESA, C.NUMERO, C.LETRA, sum( (D.IMPORTE+D.PVERDE)-((D.IMPORTE+D.PVERDE)*(C.PRONTO/100)) ) +
		round( sum(( (D.IMPORTE+D.PVERDE)-((D.IMPORTE+D.PVERDE)*(C.PRONTO/100)) )*(COALESCE(IVA.IVA,0.00)/100)),2) +
		round( sum(( (D.IMPORTE+D.PVERDE)-((D.IMPORTE+D.PVERDE)*(C.PRONTO/100)) )*(CASE WHEN CLI.RECARGO=1 THEN COALESCE(IVA.RECARG,0.00)/100 ELSE 0 END)),2) as totimpiva, IVA.iva
		FROM '+@GESTION+'.DBO.D_PEDIVE D 
		JOIN '+@GESTION+'.DBO.C_PEDIVE C ON D.EMPRESA=C.EMPRESA AND D.LETRA=C.LETRA AND LTRIM(RTRIM(D.NUMERO))=LTRIM(RTRIM(C.NUMERO))
		LEFT JOIN '+@GESTION+'.DBO.TIPO_IVA IVA ON IVA.CODIGO=D.TIPO_IVA 
		LEFT JOIN '+@GESTION+'.DBO.CLIENTES CLI ON CLI.CODIGO=C.CLIENTE
		WHERE D.EMPRESA='''+@empresa+''' AND LTRIM(RTRIM(D.NUMERO))=LTRIM(RTRIM('''+@NUMERO+''')) AND D.LETRA='''+@LETRA+'''  group by c.empresa, c.numero, c.letra, IVA.iva) a GROUP BY A.EMPRESA, A.NUMERO, A.LETRA) D ON D.EMPRESA=C.EMPRESA AND D.NUMERO=C.NUMERO AND D.LETRA=C.LETRA

/*
	SELECT @TOTALDOC = coalesce(CONVERT(DECIMAL(16,2),sum(totimpiva)),0.00) from (SELECT sum( (D.IMPORTE+D.PVERDE)-((D.IMPORTE+D.PVERDE)*(C.PRONTO/100)) ) +
	round( sum(( (D.IMPORTE+D.PVERDE)-((D.IMPORTE+D.PVERDE)*(C.PRONTO/100)) )*(COALESCE(IVA.IVA,0.00)/100)),2) +
	round( sum(( (D.IMPORTE+D.PVERDE)-((D.IMPORTE+D.PVERDE)*(C.PRONTO/100)) )*(CASE WHEN CLI.RECARGO=1 THEN COALESCE(IVA.RECARG,0.00)/100 ELSE 0 END)),2) as totimpiva, IVA.iva
	FROM '+@GESTION+'.DBO.'+@TABLEDET+' D JOIN '+@GESTION+'.DBO.'+@TABLECAB+' C ON D.EMPRESA=C.EMPRESA AND D.LETRA=C.LETRA AND LTRIM(RTRIM(D.NUMERO))=LTRIM(RTRIM(C.NUMERO))
	LEFT JOIN '+@GESTION+'.DBO.TIPO_IVA IVA ON IVA.CODIGO=D.TIPO_IVA LEFT JOIN '+@GESTION+'.DBO.CLIENTES CLI ON CLI.CODIGO=C.CLIENTE
	WHERE D.EMPRESA='''+@empresa+''' AND LTRIM(RTRIM(D.NUMERO))=LTRIM(RTRIM('''+@NUMERO+''')) AND D.LETRA='''+@LETRA+'''  group by c.empresa, c.numero, c.letra, IVA.iva) a 

	UPDATE '+@GESTION+'.DBO.'+@TABLECAB+' SET TOTALDOC=@TOTALDOC 
	WHERE EMPRESA='''+@empresa+''' AND LTRIM(RTRIM(NUMERO))=LTRIM(RTRIM('''+@NUMERO+''')) AND LETRA='''+@LETRA+'''
	*/
	'
	--print @cSQL1
	exec (@cSQL+@cSQL1)

	RETURN -1
END TRY
BEGIN CATCH 
	DECLARE @ErrorMessage NVARCHAR(4000), @ErrorSeverity INT, @ErrorState INT;  

    SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE();  

    RAISERROR (@ErrorMessage, -- Message text.  
               @ErrorSeverity, -- Severity.  
               @ErrorState -- State.  
               );  
	SET @Mensaje=@ErrorMessage+', No se han podido calcular los importes del documento'
	--PRINT(@Mensaje)
	SELECT @Mensaje AS JAVASCRIPT
    RETURN 1
END CATCH
